name: Performance Test
# https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions

on:
  pull_request:
    branches-ignore:
      - 'mona/octocat'
    paths:
      - './gitops/docker/php/'      

  push:
    branches:
      - main
      - 'releases/**'

    paths-ignore:
      - 'docs/**'  
      - '!sub-project/docs/**' # the !sub-project/docs/** pattern is used to exclude the sub-project/docs directory from the paths-ignore filter.  
    tags:
      - v2
      - v1.*      

  issues:
    types: [opened, edited]
      #- opened
    
  label:
    types:
      - created

  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 5,17 * * *'      

  workflow_call:
    inputs:
      username:
        description: 'A username passed from the caller workflow'
        default: 'john-doe'
        required: false
        type: string

jobs: 

  manual_print_username:
    runs-on: ubuntu-latest

    steps:
      - name: Print the input name to STDOUT
        run: echo The username is ${{ inputs.username }}

  schedule_test_pipe:
    runs-on: ubuntu-latest
    steps:
      - name: Not on Monday or Wednesday
        if: github.event.schedule != '30 5 * * 1,3'
        run: echo "This job runs every day at 5:30 UTC except Monday and Wednesday."
      - name: Every time
        run: echo "This step will always run"

  unit_tests_api:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x] 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Node.js dependencies
        run: npm install --package-lock-only
      - run: npm ci 

      - name: Run tests
        run: npm test